import DashboardLayout from "@/components/DashboardLayout";
import { StatusBadge } from "@/components/StatusBadge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, Bell, CheckCircle2, ClipboardList, Clock3, Download, FileClock, Inbox, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";

const dateText = (date: Date | null | undefined) => date ? new Intl.DateTimeFormat("ar-LY", { dateStyle: "medium", timeStyle: "short" }).format(new Date(date)) : "—";
const statusLabels: Record<string, string> = { new: "جديدة", referred: "محالة", in_progress: "قيد التنفيذ", completed: "منجزة", archived: "مؤرشفة" };

export default function FollowUpPage() {
  const [, setLocation] = useLocation();
  const dashboard = trpc.dashboard.followUp.useQuery(undefined, { refetchInterval: 30_000 });
  const notifications = trpc.notifications.list.useQuery(undefined, { refetchInterval: 30_000 });
  const utils = trpc.useUtils();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const data = dashboard.data;
  const [taskSearch, setTaskSearch] = useState("");
  const pending = [...(data?.active || []), ...(data?.overdue || [])].filter((row, index, rows) => rows.findIndex(item => item.record.id === row.record.id) === index);
  const normalizedSearch = taskSearch.trim().toLocaleLowerCase("ar");
  const filteredPending = normalizedSearch ? pending.filter(({ record, departmentName }) => [record.subject, record.referenceNumber, record.sourceEntity, record.destinationEntity, departmentName].filter(Boolean).some(value => String(value).toLocaleLowerCase("ar").includes(normalizedSearch))) : pending;
  const statusCounts = pending.reduce<Record<string, number>>((acc, item) => { acc[item.record.status] = (acc[item.record.status] || 0) + 1; return acc; }, {});

  return <DashboardLayout><section className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="institution-label">لوحة تشغيلية مخصصة</p><h1 className="mt-2 text-2xl font-bold text-[#17394d]">مكتب المتابعة</h1><p className="mt-2 text-xs leading-6 text-[#718793]">جميع المهام المعلقة، حالات الإنجاز، والتنبيهات الواردة للمراجعة في شاشة واحدة.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => exportPendingTasks(filteredPending)} className="h-10 border-[#cadbd6] text-xs text-[#236078]"><Download className="ml-1 h-3.5 w-3.5" />تصدير PDF</Button><Button variant="outline" onClick={() => { dashboard.refetch(); notifications.refetch(); }} className="h-10 border-[#cadbd6] text-xs text-[#236078]"><RefreshCw className="ml-1 h-3.5 w-3.5" />تحديث</Button><Button onClick={() => setLocation("/reports")} variant="outline" className="h-10 border-[#cadbd6] text-xs text-[#236078]">المؤشرات الإدارية <ArrowLeft className="mr-1 h-3.5 w-3.5" /></Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><FollowCard icon={ClipboardList} label="المهام المعلقة" value={pending.length} tone="bg-[#e8f2f4] text-[#236078]" /><FollowCard icon={ShieldAlert} label="متأخرة" value={data?.metrics.overdue || 0} tone="bg-[#fff0ed] text-[#b84a32]" /><FollowCard icon={Clock3} label="متوسط الإنجاز" value={`${data?.metrics.averageCompletionHours || 0} ساعة`} tone="bg-[#fff4dc] text-[#a36e15]" /><FollowCard icon={Bell} label="تنبيهات جديدة" value={notifications.data?.unreadCount || 0} tone="bg-[#f1eafa] text-[#765b96]" /></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(statusLabels).map(([status, label]) => <div key={status} className="institution-card flex items-center justify-between p-4"><div><p className="text-[10px] font-bold text-[#718793]">{label}</p><p className="mt-2 text-xl font-bold text-[#17394d]">{statusCounts[status] || 0}</p></div><CheckCircle2 className="h-5 w-5 text-[#5b8b71]" /></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="institution-card overflow-hidden"><div className="border-b border-[#e7ece5] px-5 py-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FileClock className="h-4 w-4 text-[#2c7284]" /><div><p className="text-sm font-bold text-[#17394d]">قائمة المهام المعلقة</p><p className="mt-1 text-[10px] text-[#78909a]">ابحث باسم المهمة أو الشخص المسؤول أو الوحدة.</p></div></div><Badge variant="secondary" className="bg-[#edf4f2] text-[10px] text-[#356474]">{filteredPending.length} من {pending.length}</Badge></div><label className="relative mt-4 block"><Search className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#7b929a]" /><input value={taskSearch} onChange={event => setTaskSearch(event.target.value)} placeholder="بحث باسم المهمة أو المسؤول..." aria-label="بحث في المهام المعلقة" className="h-10 w-full rounded-xl border border-[#d9e3de] bg-[#fbfcf9] pr-10 pl-3 text-xs text-[#17394d] outline-none transition focus:border-[#2c7284] focus:ring-2 focus:ring-[#2c7284]/15" /></label></div><div className="divide-y divide-[#edf0eb]">{dashboard.isLoading && <p className="p-8 text-center text-xs text-[#78909a]">جارٍ تحميل المهام...</p>}{!dashboard.isLoading && !filteredPending.length && <p className="p-8 text-center text-xs text-[#78909a]">{pending.length ? "لا توجد نتائج مطابقة للبحث." : "لا توجد مهام معلقة حاليًا."}</p>}{filteredPending.map(({ record, departmentName }) => <div key={record.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-[#294958]">{record.subject}</p><p className="mt-1 text-[10px] text-[#78909a]">{record.referenceNumber} · {departmentName || "غير محالة"}</p></div><StatusBadge status={record.status} /></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-[10px]"><span className={record.dueAt && new Date(record.dueAt).getTime() < Date.now() ? "font-bold text-[#bd5138]" : "text-[#718793]"}>{record.dueAt ? `استحقاق ${dateText(record.dueAt)}` : "دون تاريخ استحقاق"}</span><span className="text-[#91a1a2]">{record.sourceEntity}</span></div></div>)}</div></section>
    <section className="institution-card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e7ece5] px-5 py-4"><Bell className="h-4 w-4 text-[#765b96]" /><div><p className="text-sm font-bold text-[#17394d]">تنبيهات المراجعة</p><p className="mt-1 text-[10px] text-[#78909a]">إشعارات التقارير الجديدة الموجهة لمكتب المتابعة.</p></div></div><div className="divide-y divide-[#edf0eb]">{notifications.isLoading && <p className="p-8 text-center text-xs text-[#78909a]">جارٍ تحميل التنبيهات...</p>}{!notifications.isLoading && !notifications.data?.rows.length && <p className="p-8 text-center text-xs text-[#78909a]">لا توجد تنبيهات جديدة.</p>}{notifications.data?.rows.map(item => <button key={item.id} onClick={() => !item.readAt && markRead.mutate({ notificationId: item.id })} className={`block w-full p-4 text-right transition hover:bg-[#fbfcf9] ${item.readAt ? "opacity-60" : "bg-[#fffaf0]"}`}><div className="flex items-start gap-2"><Inbox className="mt-0.5 h-4 w-4 shrink-0 text-[#b28937]" /><div className="min-w-0"><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold text-[#294958]">{item.title}</p>{!item.readAt && <span className="h-2 w-2 rounded-full bg-[#c6533c]" />}</div><p className="mt-1 text-[10px] leading-5 text-[#78909a]">{item.content}</p><p className="mt-2 text-[9px] text-[#91a1a2]">{dateText(item.createdAt)}</p></div></div></button>)}</div></section></div>
  </section></DashboardLayout>;
}
function FollowCard({ icon: Icon, label, value, tone }: { icon: typeof ClipboardList; label: string; value: string | number; tone: string }) { return <div className="institution-card flex items-center justify-between p-5"><div><p className="institution-label">{label}</p><p className="mt-3 text-2xl font-bold text-[#17394d]">{value}</p></div><div className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div></div>; }
function RecordPanel({ title, icon: Icon, rows, loading, danger }: { title: string; icon: typeof AlertTriangle; rows: any[]; loading: boolean; danger?: boolean }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{loading ? "جارٍ التحميل..." : rows.length}</CardContent></Card>; }
void RecordPanel;
void AlertTriangle;
void dateText;

function exportPendingTasks(rows: Array<{ record: any; departmentName?: string | null }>) {
  const printWindow = window.open("", "_blank", "noopener,noreferrer");
  if (!printWindow) return;
  const safe = (value: unknown) => String(value ?? "—").replace(/[&<>\"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\\\"": "&quot;", "'": "&#039;" })[character] || character);
  const body = rows.map(({ record, departmentName }) => `<tr><td>${safe(record.referenceNumber)}</td><td>${safe(record.subject)}</td><td>${safe(statusLabels[record.status] || record.status)}</td><td>${safe(departmentName || "غير محالة")}</td><td>${safe(record.dueAt ? dateText(record.dueAt) : "دون استحقاق")}</td></tr>`).join("");
  printWindow.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>قائمة المهام المعلقة - TIDC</title><style>@page{size:A4;margin:16mm}body{font-family:Arial,Tahoma,sans-serif;color:#17394d}header{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #d0a84e;padding-bottom:14px;margin-bottom:20px}header img{width:68px;height:54px;object-fit:contain}h1{font-size:20px;margin:0 0 7px}p{margin:4px 0;font-size:11px;color:#526f7a}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#103548;color:#fff;padding:9px;text-align:right}td{border:1px solid #dfe7e2;padding:8px;vertical-align:top}footer{margin-top:18px;font-size:10px;color:#718793}@media print{button{display:none}}</style></head><body><header><img src="/manus-storage/tidc-logo_6a455ae1.png" alt="شعار المركز"><div style="text-align:center;flex:1"><p>دولة ليبيا · وزارة السياحة والصناعات التقليدية</p><h1>مركز المعلومات والتوثيق السياحي</h1><p>قائمة المهام المعلقة - مكتب المتابعة</p></div><img src="/manus-storage/ministry-logo_002815c1.png" alt="شعار الوزارة"></header><p>تاريخ التصدير: ${safe(new Intl.DateTimeFormat("ar-LY", { dateStyle: "full", timeStyle: "short" }).format(new Date()))}</p><table><thead><tr><th>الرقم الإشاري</th><th>الموضوع</th><th>الحالة</th><th>الوحدة</th><th>الاستحقاق</th></tr></thead><tbody>${body || `<tr><td colspan="5" style="text-align:center">لا توجد مهام معلقة حاليًا</td></tr>`}</tbody></table><footer>وثيقة مولدة من نظام الأرشفة الإلكترونية - TIDC</footer><script>window.onload=()=>{window.print();}</script></body></html>`);
  printWindow.document.close();
}
