import DashboardLayout from "@/components/DashboardLayout";
import { StatusBadge } from "@/components/StatusBadge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, Bell, CheckCircle2, ClipboardList, Clock3, FileClock, Inbox, RefreshCw, ShieldAlert } from "lucide-react";
import { useLocation } from "wouter";

const dateText = (date: Date | null | undefined) => date ? new Intl.DateTimeFormat("ar-LY", { dateStyle: "medium", timeStyle: "short" }).format(new Date(date)) : "—";
const statusLabels: Record<string, string> = { new: "جديدة", referred: "محالة", in_progress: "قيد التنفيذ", completed: "منجزة", archived: "مؤرشفة" };

export default function FollowUpPage() {
  const [, setLocation] = useLocation();
  const dashboard = trpc.dashboard.followUp.useQuery(undefined, { refetchInterval: 30_000 });
  const notifications = trpc.notifications.list.useQuery(undefined, { refetchInterval: 30_000 });
  const utils = trpc.useUtils();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const data = dashboard.data;
  const pending = [...(data?.active || []), ...(data?.overdue || [])].filter((row, index, rows) => rows.findIndex(item => item.record.id === row.record.id) === index);
  const statusCounts = pending.reduce<Record<string, number>>((acc, item) => { acc[item.record.status] = (acc[item.record.status] || 0) + 1; return acc; }, {});

  return <DashboardLayout><section className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="institution-label">لوحة تشغيلية مخصصة</p><h1 className="mt-2 text-2xl font-bold text-[#17394d]">مكتب المتابعة</h1><p className="mt-2 text-xs leading-6 text-[#718793]">جميع المهام المعلقة، حالات الإنجاز، والتنبيهات الواردة للمراجعة في شاشة واحدة.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { dashboard.refetch(); notifications.refetch(); }} className="h-10 border-[#cadbd6] text-xs text-[#236078]"><RefreshCw className="ml-1 h-3.5 w-3.5" />تحديث</Button><Button onClick={() => setLocation("/reports")} variant="outline" className="h-10 border-[#cadbd6] text-xs text-[#236078]">المؤشرات الإدارية <ArrowLeft className="mr-1 h-3.5 w-3.5" /></Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><FollowCard icon={ClipboardList} label="المهام المعلقة" value={pending.length} tone="bg-[#e8f2f4] text-[#236078]" /><FollowCard icon={ShieldAlert} label="متأخرة" value={data?.metrics.overdue || 0} tone="bg-[#fff0ed] text-[#b84a32]" /><FollowCard icon={Clock3} label="متوسط الإنجاز" value={`${data?.metrics.averageCompletionHours || 0} ساعة`} tone="bg-[#fff4dc] text-[#a36e15]" /><FollowCard icon={Bell} label="تنبيهات جديدة" value={notifications.data?.unreadCount || 0} tone="bg-[#f1eafa] text-[#765b96]" /></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(statusLabels).map(([status, label]) => <div key={status} className="institution-card flex items-center justify-between p-4"><div><p className="text-[10px] font-bold text-[#718793]">{label}</p><p className="mt-2 text-xl font-bold text-[#17394d]">{statusCounts[status] || 0}</p></div><CheckCircle2 className="h-5 w-5 text-[#5b8b71]" /></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="institution-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e7ece5] px-5 py-4"><div className="flex items-center gap-2"><FileClock className="h-4 w-4 text-[#2c7284]" /><div><p className="text-sm font-bold text-[#17394d]">قائمة المهام المعلقة</p><p className="mt-1 text-[10px] text-[#78909a]">مرتبة حسب الحالة وتاريخ الاستحقاق لمراجعة أسرع.</p></div></div><Badge variant="secondary" className="bg-[#edf4f2] text-[10px] text-[#356474]">{pending.length} مهمة</Badge></div><div className="divide-y divide-[#edf0eb]">{dashboard.isLoading && <p className="p-8 text-center text-xs text-[#78909a]">جارٍ تحميل المهام...</p>}{!dashboard.isLoading && !pending.length && <p className="p-8 text-center text-xs text-[#78909a]">لا توجد مهام معلقة حاليًا.</p>}{pending.map(({ record, departmentName }) => <div key={record.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-[#294958]">{record.subject}</p><p className="mt-1 text-[10px] text-[#78909a]">{record.referenceNumber} · {departmentName || "غير محالة"}</p></div><StatusBadge status={record.status} /></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-[10px]"><span className={record.dueAt && new Date(record.dueAt).getTime() < Date.now() ? "font-bold text-[#bd5138]" : "text-[#718793]"}>{record.dueAt ? `استحقاق ${dateText(record.dueAt)}` : "دون تاريخ استحقاق"}</span><span className="text-[#91a1a2]">{record.sourceEntity}</span></div></div>)}</div></section>
    <section className="institution-card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e7ece5] px-5 py-4"><Bell className="h-4 w-4 text-[#765b96]" /><div><p className="text-sm font-bold text-[#17394d]">تنبيهات المراجعة</p><p className="mt-1 text-[10px] text-[#78909a]">إشعارات التقارير الجديدة الموجهة لمكتب المتابعة.</p></div></div><div className="divide-y divide-[#edf0eb]">{notifications.isLoading && <p className="p-8 text-center text-xs text-[#78909a]">جارٍ تحميل التنبيهات...</p>}{!notifications.isLoading && !notifications.data?.rows.length && <p className="p-8 text-center text-xs text-[#78909a]">لا توجد تنبيهات جديدة.</p>}{notifications.data?.rows.map(item => <button key={item.id} onClick={() => !item.readAt && markRead.mutate({ notificationId: item.id })} className={`block w-full p-4 text-right transition hover:bg-[#fbfcf9] ${item.readAt ? "opacity-60" : "bg-[#fffaf0]"}`}><div className="flex items-start gap-2"><Inbox className="mt-0.5 h-4 w-4 shrink-0 text-[#b28937]" /><div className="min-w-0"><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold text-[#294958]">{item.title}</p>{!item.readAt && <span className="h-2 w-2 rounded-full bg-[#c6533c]" />}</div><p className="mt-1 text-[10px] leading-5 text-[#78909a]">{item.content}</p><p className="mt-2 text-[9px] text-[#91a1a2]">{dateText(item.createdAt)}</p></div></div></button>)}</div></section></div>
  </section></DashboardLayout>;
}
function FollowCard({ icon: Icon, label, value, tone }: { icon: typeof ClipboardList; label: string; value: string | number; tone: string }) { return <div className="institution-card flex items-center justify-between p-5"><div><p className="institution-label">{label}</p><p className="mt-3 text-2xl font-bold text-[#17394d]">{value}</p></div><div className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div></div>; }
function RecordPanel({ title, icon: Icon, rows, loading, danger }: { title: string; icon: typeof AlertTriangle; rows: any[]; loading: boolean; danger?: boolean }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{loading ? "جارٍ التحميل..." : rows.length}</CardContent></Card>; }
void RecordPanel;
void AlertTriangle;
void dateText;
