import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FilePlus2, Gavel, Loader2, ScrollText, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type OfficialType = "decision" | "circular";
const dateText = (date: Date) => new Intl.DateTimeFormat("ar-LY", { year: "numeric", month: "short", day: "numeric" }).format(new Date(date));

export default function OfficialDocumentsPage({ type }: { type: OfficialType }) {
  const [open, setOpen] = useState(false); const { data: caps } = trpc.access.capabilities.useQuery(); const decisions = trpc.decisions.list.useQuery(undefined, { enabled: type === "decision" }); const circulars = trpc.circulars.list.useQuery(undefined, { enabled: type === "circular" }); const rows = type === "decision" ? decisions.data : circulars.data; const title = type === "decision" ? "القرارات الإدارية" : "المناشير الداخلية"; const Icon = type === "decision" ? Gavel : ScrollText;
  return <DashboardLayout><section className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="institution-label">وثائق رسمية</p><h1 className="mt-2 text-2xl font-bold text-[#17394d]">{title}</h1><p className="mt-2 text-xs leading-6 text-[#718793]">ترقيم سنوي متسلسل وربط اختياري بسجل المراسلات المرجعي.</p></div>{caps?.canCreateDecisionOrCircular && <Button onClick={() => setOpen(true)} className="h-11 bg-[#103548] px-5 text-white hover:bg-[#17475d]"><FilePlus2 className="ml-2 h-4 w-4" />إصدار {type === "decision" ? "قرار" : "منشور"}</Button>}</div><div className="institution-card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e7ece5] px-5 py-4"><Icon className="h-4 w-4 text-[#b28937]" /><p className="text-sm font-bold text-[#17394d]">السجل الرسمي</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right"><thead className="bg-[#f8faf7]"><tr className="text-[10px] font-bold text-[#718793]"><th className="px-5 py-4">الرقم الرسمي</th><th className="px-5 py-4">الموضوع</th><th className="px-5 py-4">تاريخ {type === "decision" ? "النفاذ" : "الإصدار"}</th><th className="px-5 py-4">الحالة</th></tr></thead><tbody>{(type === "decision" ? decisions.isLoading : circulars.isLoading) && <tr><td colSpan={4} className="p-10 text-center text-xs text-[#78909a]">جارٍ تحميل السجل...</td></tr>}{rows?.length === 0 && <tr><td colSpan={4} className="p-12 text-center text-xs text-[#78909a]">لا توجد وثائق رسمية مسجلة حاليًا.</td></tr>}{type === "decision" && (rows as any[])?.map(row => <tr key={row.id} className="border-t border-[#edf0eb] hover:bg-[#fbfcf9]"><td className="px-5 py-4 text-xs font-bold text-[#235b70]">{row.decisionNumber}</td><td className="px-5 py-4 text-xs font-bold text-[#284756]">{row.subject}</td><td className="px-5 py-4 text-[10px] text-[#718793]">{dateText(row.effectiveDate)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${row.legalStatus === "active" ? "bg-emerald-50 text-emerald-700" : row.legalStatus === "amended" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}>{row.legalStatus === "active" ? "ساري" : row.legalStatus === "amended" ? "معدّل" : "ملغى"}</span></td></tr>)}{type === "circular" && (rows as any[])?.map(row => <tr key={row.id} className="border-t border-[#edf0eb] hover:bg-[#fbfcf9]"><td className="px-5 py-4 text-xs font-bold text-[#235b70]">{row.circularNumber}</td><td className="px-5 py-4 text-xs font-bold text-[#284756]">{row.subject}</td><td className="px-5 py-4 text-[10px] text-[#718793]">{dateText(row.issueDate)}</td><td className="px-5 py-4"><span className="rounded-full bg-[#e9f2f0] px-2.5 py-1 text-[10px] font-bold text-[#2e716d]">صادر</span></td></tr>)}</tbody></table></div></div></section><OfficialForm type={type} open={open} onOpenChange={setOpen} /></DashboardLayout>;
}

function OfficialForm({ type, open, onOpenChange }: { type: OfficialType; open: boolean; onOpenChange: (value: boolean) => void }) {
  const { data: departments } = trpc.catalog.departments.useQuery(); const utils = trpc.useUtils(); const [subject, setSubject] = useState(""); const [bodyText, setBodyText] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [departmentId, setDepartmentId] = useState("none"); const [sourceId, setSourceId] = useState(""); const [targets, setTargets] = useState<number[]>([]);
  const decision = trpc.decisions.create.useMutation({ onSuccess: result => { utils.decisions.list.invalidate(); toast.success(`تم تسجيل القرار بالرقم ${result.decisionNumber}`); onOpenChange(false); reset(); }, onError: error => toast.error(error.message) }); const circular = trpc.circulars.create.useMutation({ onSuccess: result => { utils.circulars.list.invalidate(); toast.success(`تم تسجيل المنشور بالرقم ${result.circularNumber}`); onOpenChange(false); reset(); }, onError: error => toast.error(error.message) }); const reset = () => { setSubject(""); setBodyText(""); setDepartmentId("none"); setSourceId(""); setTargets([]); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (subject.trim().length < 3) return toast.error("يرجى إدخال موضوع الوثيقة."); const common = { subject, bodyText: bodyText || undefined, issuingDepartmentId: departmentId === "none" ? undefined : Number(departmentId), sourceCorrespondenceId: sourceId ? Number(sourceId) : undefined }; if (type === "decision") decision.mutate({ ...common, effectiveDate: new Date(`${date}T00:00:00`) }); else circular.mutate({ ...common, issueDate: new Date(`${date}T00:00:00`), targetDepartmentIds: targets }); };
  const pending = decision.isPending || circular.isPending; const label = type === "decision" ? "قرار إداري" : "منشور داخلي";
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto" dir="rtl"><DialogHeader><DialogTitle>إصدار {label}</DialogTitle><DialogDescription>يُنشأ الرقم الرسمي بشكل سنوي ومتسلسل عند الحفظ.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-5 pt-3"><div className="grid gap-4 sm:grid-cols-2"><Field label="الموضوع"><Input value={subject} onChange={event => setSubject(event.target.value)} placeholder="عنوان الوثيقة الرسمية" /></Field><Field label={type === "decision" ? "تاريخ النفاذ" : "تاريخ الإصدار"}><Input type="date" value={date} onChange={event => setDate(event.target.value)} required /></Field><Field label="الإدارة المصدرة"><Select value={departmentId} onValueChange={setDepartmentId}><SelectTrigger><SelectValue placeholder="اختيار الإدارة" /></SelectTrigger><SelectContent><SelectItem value="none">غير محددة</SelectItem>{departments?.map(department => <SelectItem key={department.id} value={String(department.id)}>{department.nameAr}</SelectItem>)}</SelectContent></Select></Field><Field label="رقم المراسلة المرجعية (اختياري)"><Input inputMode="numeric" value={sourceId} onChange={event => setSourceId(event.target.value.replace(/\D/g, ""))} placeholder="المعرّف الداخلي للمراسلة" /></Field></div><Field label="النص أو الملخص المفهرس"><Textarea rows={5} value={bodyText} onChange={event => setBodyText(event.target.value)} placeholder="نص الوثيقة أو ملخصها لتفعيل البحث باللغة العربية." /></Field>{type === "circular" && <div className="rounded-2xl border border-[#dce6df] bg-[#f9fbf8] p-4"><p className="text-xs font-bold text-[#264858]">الجهات المخاطبة</p><p className="mt-1 text-[10px] text-[#78909a]">حدد الإدارات التي يجب أن تستلم المنشور.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{departments?.map(department => <label key={department.id} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-[10px] text-[#4a6875]"><Checkbox checked={targets.includes(department.id)} onCheckedChange={checked => setTargets(current => checked ? [...current, department.id] : current.filter(id => id !== department.id))} />{department.nameAr}</label>)}</div></div>}<div className="flex justify-end gap-3 border-t border-[#e8ece7] pt-5"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>إلغاء</Button><Button type="submit" disabled={pending} className="bg-[#103548] text-white hover:bg-[#17475d]">{pending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}اعتماد التسجيل</Button></div></form></DialogContent></Dialog>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label className="text-[11px] font-bold text-[#496572]">{label}</Label>{children}</div>; }
