import DashboardLayout from "@/components/DashboardLayout";
import { ReportsHeading } from "@/components/ReportsHeading";
import { trpc } from "@/lib/trpc";
import { AlertCircle, BarChart3, BellRing, Building2, FileBarChart, Landmark, PieChart as PieChartIcon, Send, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const COLORS = ["#2d7484", "#d0a84e", "#527c52", "#7b698e"];
const number = new Intl.NumberFormat("ar-LY");

export default function ReportsPage() {
  const analytics = trpc.reports.analytics.useQuery(undefined, { retry: false });
  const total = analytics.data?.documentTypes.reduce((sum, item) => sum + item.count, 0) || 0;
  const incoming = analytics.data?.documentTypes.find(item => item.key === "incoming")?.count || 0;
  const outgoing = analytics.data?.documentTypes.find(item => item.key === "outgoing")?.count || 0;
  const submitForReview = trpc.reports.submitForReview.useMutation({ onSuccess: result => toast.success(result.recipients ? `تم إرسال التنبيه إلى ${result.recipients} من مديري مكتب المتابعة.` : "تم تسجيل الطلب دون وجود حساب متابعة نشط."), onError: error => toast.error(error.message) });

  return <DashboardLayout><section className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><ReportsHeading /><Button disabled={submitForReview.isPending} onClick={() => submitForReview.mutate({ title: "تقرير جديد بانتظار المراجعة", content: `تم تقديم تقرير المؤشرات الإدارية للمراجعة بتاريخ ${new Intl.DateTimeFormat("ar-LY", { dateStyle: "medium" }).format(new Date())}.` })} className="bg-[#103548] text-white hover:bg-[#17475d]"><BellRing className="ml-2 h-4 w-4" />إرسال للمراجعة</Button></div>
    {analytics.error && <div className="flex items-center gap-3 rounded-2xl border border-rose-100 bg-rose-50 p-5 text-xs text-rose-800"><AlertCircle className="h-5 w-5 shrink-0" /><span>{analytics.error.message}</span></div>}
    {!analytics.error && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={FileBarChart} label="إجمالي الوثائق" value={number.format(total)} tone="bg-[#e8f2f4] text-[#236078]" /><Metric icon={Send} label="البريد الوارد" value={number.format(incoming)} tone="bg-sky-50 text-sky-700" /><Metric icon={Send} label="البريد الصادر" value={number.format(outgoing)} tone="bg-amber-50 text-amber-700" /><Metric icon={BarChart3} label="قرارات ومناشير" value={number.format((analytics.data?.documentTypes.find(item => item.key === "decision")?.count || 0) + (analytics.data?.documentTypes.find(item => item.key === "circular")?.count || 0))} tone="bg-emerald-50 text-emerald-700" /></div>
      <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><ChartCard icon={PieChartIcon} title="توزيع الوثائق حسب النوع" subtitle="الوارد والصادر والقرارات والمناشير"><div className="h-[300px]">{analytics.isLoading ? <LoadingChart /> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.data?.documentTypes || []} dataKey="count" nameKey="label" innerRadius={58} outerRadius={98} paddingAngle={3}>{(analytics.data?.documentTypes || []).map((entry, index) => <Cell key={entry.key} fill={COLORS[index]} />)}</Pie><Tooltip formatter={value => number.format(Number(value))} /><Legend verticalAlign="bottom" iconType="circle" wrapperStyle={{ fontSize: 10, direction: "rtl" }} /></PieChart></ResponsiveContainer>}</div></ChartCard><ChartCard icon={Building2} title="الرسائل الواردة والصادرة لكل إدارة" subtitle="يُظهر الحمل التشغيلي المتراكم حسب الإدارة"><div className="h-[300px]">{analytics.isLoading ? <LoadingChart /> : <DistributionBar data={analytics.data?.byDepartment || []} />}</div></ChartCard></div>
      <div className="grid gap-6 xl:grid-cols-2"><ChartCard icon={Landmark} title="الرسائل حسب المكاتب" subtitle="يُظهر البريد الوارد والصادر المسجل لدى كل مكتب"><div className="h-[300px]">{analytics.isLoading ? <LoadingChart /> : <DistributionBar data={analytics.data?.byOffice || []} />}</div></ChartCard><ChartCard icon={UsersRound} title="الرسائل حسب الجهات" subtitle="أكثر الجهات المرسلة أو المستقبلة للمعاملات"><div className="h-[300px]">{analytics.isLoading ? <LoadingChart /> : <DistributionBar data={analytics.data?.byEntity || []} />}</div></ChartCard></div>
      <section className="institution-card overflow-hidden"><div className="border-b border-[#e7ece5] px-5 py-4"><p className="text-sm font-bold text-[#17394d]">الملخص العددي للوثائق</p><p className="mt-1 text-[10px] text-[#78909a]">قراءة تفصيلية للمؤشرات المستخدمة في الرسومات.</p></div><div className="grid divide-y divide-[#edf0eb] sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{analytics.data?.documentTypes.map((item, index) => <div key={item.key} className="p-5"><div className="flex items-center justify-between"><span className="text-[11px] font-bold text-[#46616f]">{item.label}</span><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index] }} /></div><p className="mt-3 text-2xl font-bold text-[#17394d]">{number.format(item.count)}</p><p className="mt-1 text-[10px] text-[#8aa0a8]">وثيقة مسجلة</p></div>)}</div></section></>}
  </section></DashboardLayout>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof FileBarChart; label: string; value: string; tone: string }) { return <div className="institution-card flex items-center justify-between p-5"><div><p className="institution-label">{label}</p><p className="mt-3 text-xl font-bold text-[#17394d]">{value}</p></div><div className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div></div>; }
function ChartCard({ icon: Icon, title, subtitle, children }: { icon: typeof BarChart3; title: string; subtitle: string; children: React.ReactNode }) { return <section className="institution-card overflow-hidden"><div className="flex items-start gap-3 border-b border-[#e7ece5] px-5 py-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf5f2] text-[#357584]"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-bold text-[#17394d]">{title}</p><p className="mt-1 text-[10px] leading-5 text-[#78909a]">{subtitle}</p></div></div><div className="p-4">{children}</div></section>; }
function DistributionBar({ data }: { data: { name: string; incoming: number; outgoing: number; total: number }[] }) { if (!data.length) return <EmptyChart />; return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ top: 8, right: 8, left: 6, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5ece7" /><XAxis type="number" tick={{ fontSize: 10, fill: "#6c838b" }} allowDecimals={false} /><YAxis type="category" dataKey="name" width={100} tick={{ fontSize: 9, fill: "#47616e" }} /><Tooltip formatter={value => number.format(Number(value))} contentStyle={{ borderRadius: 12, fontSize: 11, direction: "rtl" }} /><Legend wrapperStyle={{ fontSize: 10, direction: "rtl" }} /><Bar dataKey="incoming" name="وارد" fill="#2d7484" radius={[0, 4, 4, 0]} /><Bar dataKey="outgoing" name="صادر" fill="#d0a84e" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer>; }
function LoadingChart() { return <div className="grid h-full place-items-center text-xs text-[#78909a]">جارٍ احتساب الإحصاءات...</div>; }
function EmptyChart() { return <div className="grid h-full place-items-center rounded-xl bg-[#f8faf7] px-6 text-center text-[11px] leading-6 text-[#78909a]">لا توجد سجلات كافية ضمن هذا التصنيف. ستظهر الرسومات تلقائيًا عند تسجيل وإحالة المعاملات.</div>; }
